version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: app_frontend
    volumes:
      - /workspace/node_modules
      - ./frontend:/workspace
    stdin_open: true

  nginx: 
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: app_nginx
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes:
      - /workspace/node_modules
      - ./backend:/workspace
    
  mysql:
    restart: unless-stopped
    build:
      context: ./mysql
      dockerfile: Dockerfile.dev
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: myapp
